# 项目相关配置
ld:
  # 名称
  name: lingd
  # 版本
  version: 1.0.0
  # 版权年份
  copyrightYear: 2024
  # 文件路径 示例（ Windows配置D:/ld/uploadPath，Linux配置 /home/ld/uploadPath）
  profile: /home/ld/uploadPath
  # 获取ip地址开关
  addressEnabled: false
  # 验证码类型 math 数字计算 char 字符验证
  captchaType: math

# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8080
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100

# 日志配置
logging:
  level:
    com.ld: debug
    org.springframework: warn

# 用户配置
user:
  password:
    # 密码最大错误次数
    maxRetryCount: 5
    # 密码锁定时间（默认10分钟）
    lockTime: 10

# Spring配置
spring:
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  profiles:
    active: druid
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 10MB
      # 设置总上传的文件大小
      max-request-size: 20MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  # redis 配置
  redis:
    enabled: false
    # 地址
    host: localhost
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 0
    # 密码
    password:
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 30

# MyBatis配置
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.ld.**.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql

# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true
  # 请求前缀
  pathMapping: /dev-api

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*

# 大模型接口
llm:
  # qwen, zpai, minimax
  type: qwen
  chat:
    zpai:
      url: https://api.zpai.cn/v1/chat/completions
      apiKey:
    minimax:
      url: https://api.minimax.chat/v1/text/chatcompletion_v2
      groupId: 1793262119999783547
      apiKey: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJHcm91cE5hbWUiOiLnjovmgboiLCJVc2VyTmFtZSI6IueOi-aBuiIsIkFjY291bnQiOiIiLCJTdWJqZWN0SUQiOiIxNzkzMjYyMTIwMDA4MTcyMTU1IiwiUGhvbmUiOiIxMzYyNjcxMDA1NCIsIkdyb3VwSUQiOiIxNzkzMjYyMTE5OTk5NzgzNTQ3IiwiUGFnZU5hbWUiOiIiLCJNYWlsIjoiIiwiQ3JlYXRlVGltZSI6IjIwMjQtMDctMDMgMTE6MDM6MzYiLCJpc3MiOiJtaW5pbWF4In0.IDkJq5GVLatSSx4IA-fgGSMqnOXO0UnQQuaXfRNkm7cJPol7JhbMm8f4HFA3yoxaN-GxkMyV1ASyu6kEd8LMbeBuyMQ6d9uAKYRUjloJLYMfIkYmnicuUJ7RFWTBXHSSlh1AoD4qEWrd_DxyDMdHvCN62tGarXhVSpxQWFCFF2LVOirkuzXUONTuOfZFB6Kf4yc7t5bK6r7r4AoOnL_z6VHMcGH0sdI38u61tx3WWcLMk_zw6a3LCcK2_QuS8brq5IUFxNRPiHvMH3D8wcXb2ZV0Euhptb9UADMsN3aFbqY2oKGNfoSTKcoZCHK0LK0yIRW-RQsnUkwAXdjvW6G8hA
    qwen:
      apiKey: sk-54c8ed67004d4c0c894f3247641ac931